### ISSUE TITLE
Create AddQuestions component

### ISSUE THREAD

**Issue by andrewtchan** [hack4impact-calpoly/cp-ccc-uss#16]
Make a component called AddQuestions. This will be a child of the CreateEvent component and it corresponds to the bottom half of the CreateEvent design seen below. It allows an admin to add custom questions to the Event form (VolunteerForm object). It will show up initially as just the "add question" button, but expand (scrollable) as the admin adds more questions.

Figma: https://www.figma.com/file/Z4ehMEyfixqSX5K5EJZ9ID/ccuss-project?type=design&node-id=128-400&mode=design&t=VSaK84qfttjxs3Qc-0 

![Image](https://github.com/hack4impact-calpoly/cp-ccc-uss/assets/102489587/71c72eca-256f-48c2-987d-a1c65ce4d5e9)

- [ ] Support for short answer questions
- [ ] Support for multiple choice questions
- [ ] Contain questions in a scrollable container (so it fits in the `CreateEvent` modal)

Notes/tips:
- Reference the `VolunteerForm` schema to see what data we need to capture (array of questions attached to an Event)
- Each question has the actual `question` being asked, the question format `fieldType`, and optionally, `options?` which will contain the valid options for multiple choice questions
- Assume you have a `questions` state variable and `setQuestions` function from a `useState` passed as a prop to your component from the `CreateEvent` parent component. However, you can just put this `useState` in your component so you can test if your rendering works for now
- This will be where you store the newly created questions so they show up in the modal and is easily accessible for when we eventually make a POST request to create a new `VolunteerForm` with this data
- Reference the dimensions in the Figma so it fits in the `CreateEvent` modal

**Comment by hnadrian** [comment]
<img width="480" alt="Screenshot 2024-03-06 at 6 39 34 PM" src="https://github.com/hack4impact-calpoly/cp-ccc-uss/assets/73419144/8a67d5b0-20eb-42ea-a14e-26a4ec32ce1b">

- Workflow has been re done to add an option first before entering the option
- Converted to ChakraUI code
- Added figma design
