### ISSUE TITLE
Research calendar development

### ISSUE THREAD

**Issue by hnadrian** [hack4impact-calpoly/cp-ccc-uss#2]
- [x] Research libraries, pick 1-2

- Find out how to link components to calendars (want to be able to expand a calendar event into its page/modal)
- How to add, delete, and edit items on the calendar

- [x] Create a very basic prototype

- Make a Calendar page under components/ to test

**Comment by charlesmoreno32** [comment]
Right now, the events are a hardcoded array passed into the FullCalendar Component. I think that we can store each of the events in a database and pass a list of them to the component when rendering it. Then the add, delete and edit apis will interact with the database, maybe needing to refresh the calendar each time an action is taken.
