### ISSUE TITLE
Create endpoints for Event

### ISSUE THREAD

**Issue by hnadrian** [hack4impact-calpoly/cp-ccc-uss#5]
Create the following endpoints with the specified URLs:

- [x] Create Event (api/event) POST
- [x] Retrieve all events (../api/event) GET
- [x] Retrieve one specific event (../api/event/\<id\>) GET
- [x] Get all VolunteerRoles for one event (../api/event/\<id\>/role) GET
- [x] Edit an Event (../api/event/\<id\>) PUT
- [x] Delete an Event (../api/event/\<id\>) DELETE

**Comment by andrewtchan** [comment]
waiting for schemas #6

**Comment by andrewtchan** [comment]
schemas are now on main, feel free to start now and let us know if you have questions about anything!!
