### ISSUE TITLE
Add Profile Database Page Stylings

### ISSUE THREAD

**Issue by hnadrian** [hack4impact-calpoly/cp-ccc-uss#57]
Check out app/admin/profiles. Page.tsx is the profile database page and it references ProfileDatabase.module.css. Take a look at the ThemeProvider (line 93 in page.tsx) and the createTheme() function imported from @mui/material/styles. 
![image](https://github.com/hack4impact-calpoly/cp-ccc-uss/assets/102489587/89fd4164-099f-458f-86ea-9918b79fe338)
Use the design as a reference point but please feel free to be creative, and know that some things will be easier/harder styling-wise within the MUI design philosophy/framework. Let us know if you have any questions!

**Comment by andrewtchan** [comment]
#47 was merged to develop, @xgarcia17 you can start this now, thank you!!
