### ISSUE TITLE
Add and fix Calendar Styling

### ISSUE THREAD

**Issue by hnadrian** [hack4impact-calpoly/cp-ccc-uss#77]
- [x] some of the cells get really tall for some reason, pls fix
- [x] disable drag and drop of events (!!)
- [x] make event names fit in cells + larger text? (html tooltip or expanded event cell on hover?)
- [x] shouldnt be any scrolling on the home page (calendar should fit)
- [ ] move the event sign up button (signed in volunteer view) to be inline with other calendar buttons

- the calendar/cell sizing is the highest priority here, really want the calendar to fit without having to scroll

**Comment by xgarcia17** [comment]
For <fitting event name in bubble> and <fixed cell size>

![image](https://github.com/hack4impact-calpoly/cp-ccc-uss/assets/102645280/ad036ffd-7f58-4043-a958-806804b42981)
![image](https://github.com/hack4impact-calpoly/cp-ccc-uss/assets/102645280/087f9f47-66c6-40de-8977-091917e645b0)
![image](https://github.com/hack4impact-calpoly/cp-ccc-uss/assets/102645280/9e071444-6213-486b-84f8-f9c274da27ac)
